export interface CategoryItem {
  id: string;
  name: string;
  slug: string;
  order: number;
}

export interface ProductItem {
  id: string;
  name: string;
  categoryName: string;
  subCategory: string;
  price: number;
  multiPrice?: string | null;
  image: string;
  description: string;
  unit: string;
  isAvailable: boolean;
  isFeatured: boolean;
  createdAt?: string;
  updatedAt?: string;
  categoryId?: string | null;
}

export const DEFAULT_CATEGORIES: CategoryItem[] = [
  { id: "cat-chanh", name: "Trạm Chanh", slug: "tram-chanh", order: 1 },
  { id: "cat-sua", name: "Trạm Sữa", slug: "tram-sua", order: 2 },
  { id: "cat-banh", name: "Trạm Bánh", slug: "tram-banh", order: 3 },
];

export const DEFAULT_PRODUCTS: ProductItem[] = [
  // --- TRẠM CHANH ---
  {
    id: "prod-chanh-1",
    name: "Trà Olong - Chanh tươi",
    categoryName: "Trạm Chanh, Trạm Sữa",
    subCategory: "Trà Olong Trái Cây",
    image: "/images/products/trachanh.png",
    price: 20000,
    isFeatured: true,
    isAvailable: true,
    unit: "Ly",
    description: "Trà Olong cao cấp kết hợp vị chua thanh mát của chanh tươi tự nhiên, thơm ngọt dịu dàng.",
  },
  {
    id: "prod-chanh-2",
    name: "Trà Olong - Xoài",
    categoryName: "Trạm Chanh, Trạm Sữa",
    subCategory: "Trà Olong Trái Cây",
    image: "/images/products/traxoai.png",
    price: 30000,
    isFeatured: true,
    isAvailable: true,
    unit: "Ly",
    description: "Thơm ngọt vị xoài chín nhiệt đới quyện cùng nền trà Olong đậm đà giải nhiệt sảng khoái.",
  },
  {
    id: "prod-chanh-3",
    name: "Trà Olong - Chanh dây",
    categoryName: "Trạm Chanh",
    subCategory: "Trà Olong Trái Cây",
    image: "/images/products/trachanhday.png",
    price: 30000,
    isFeatured: false,
    isAvailable: true,
    unit: "Ly",
    description: "Vị chanh dây đậm đà bừng tỉnh mọi giác quan giữa tiết trời se lạnh Đà Lạt.",
  },
  {
    id: "prod-chanh-4",
    name: "Trà Olong - Quả mọng",
    categoryName: "Trạm Chanh",
    subCategory: "Trà Olong Trái Cây",
    image: "/images/products/traquamong.png",
    price: 30000,
    isFeatured: true,
    isAvailable: true,
    unit: "Ly",
    description: "Sự kết hợp giữa dâu tây và quả mọng đỏ ngọt thanh, giải nhiệt tuyệt đối.",
  },
  {
    id: "prod-chanh-5",
    name: "Trà Olong - Mãng cầu",
    categoryName: "Trạm Chanh, Trạm Sữa",
    subCategory: "Trà Olong Trái Cây",
    image: "/images/products/tramangcau.png",
    price: 30000,
    isFeatured: false,
    isAvailable: true,
    unit: "Ly",
    description: "Mãng cầu xiêm tươi dầm kết hợp trà Olong thanh tao, chua ngọt hấp dẫn.",
  },
  {
    id: "prod-chanh-6",
    name: "Trà Olong - Đào",
    categoryName: "Trạm Chanh",
    subCategory: "Trà Olong Trái Cây",
    image: "/images/products/tradao.png",
    price: 30000,
    isFeatured: false,
    isAvailable: true,
    unit: "Ly",
    description: "Trà đào thơm nức giòn ngọt thanh mát, miếng đào giòn sần sật chuẩn vị.",
  },
  {
    id: "prod-chanh-7",
    name: "Thêm thạch dừa / thạch chanh",
    categoryName: "Trạm Chanh",
    subCategory: "Topping Thêm",
    image: "/images/products/thach.png",
    price: 5000,
    isFeatured: false,
    isAvailable: true,
    unit: "Phần",
    description: "Topping giòn dai sần sật ăn kèm trà cực đã.",
  },
  {
    id: "prod-chanh-8",
    name: "Lăn Truyền Thống",
    categoryName: "Trạm Chanh",
    subCategory: "Bánh Lăn Nướng",
    image: "/images/products/banhlanlon.png",
    price: 20000,
    multiPrice: "20k - 30k",
    isFeatured: true,
    isAvailable: true,
    unit: "Cái",
    description: "Bánh lăn nướng vỏ giòn thơm bùi mùi bơ sữa trứng đặc sản Trạm Chanh.",
  },
  {
    id: "prod-chanh-9",
    name: "Lăn Phô Mai Chảy",
    categoryName: "Trạm Chanh",
    subCategory: "Bánh Lăn Nướng",
    image: "/images/products/banhlanvua.png",
    price: 15000,
    multiPrice: "Từ 15k",
    isFeatured: true,
    isAvailable: true,
    unit: "Cái",
    description: "Nhân phô mai béo ngậy tan chảy kích thích vị giác thơm nức khi mới ra lò.",
  },
  {
    id: "prod-chanh-10",
    name: "Lăn Choco Chip",
    categoryName: "Trạm Chanh",
    subCategory: "Bánh Lăn Nướng",
    image: "/images/products/banhlannho.png",
    price: 15000,
    multiPrice: "Từ 15k",
    isFeatured: false,
    isAvailable: true,
    unit: "Cái",
    description: "Vỏ thơm bùi kèm hạt chocolate chip ngọt ngào quyến rũ.",
  },
  {
    id: "prod-chanh-11",
    name: "Lăn Cốm dẻo",
    categoryName: "Trạm Chanh",
    subCategory: "Bánh Lăn Nướng",
    image: "/images/products/banhlanlon.png",
    price: 15000,
    multiPrice: "Từ 15k",
    isFeatured: false,
    isAvailable: true,
    unit: "Cái",
    description: "Hương cốm non thơm dịu dẻo thơm truyền thống nướng vàng ruộm.",
  },

  // --- TRẠM SỮA ---
  {
    id: "prod-sua-1",
    name: "Sữa bò tươi - Đậu nành hạt điều",
    categoryName: "Trạm Sữa",
    subCategory: "Sữa Hạt Tươi",
    image: "/images/products/suadaunanhhanhnhan.png",
    price: 18000,
    isFeatured: true,
    isAvailable: true,
    unit: "Ly",
    description: "Sữa bò tươi nguyên chất nấu cùng đậu nành hữu cơ và hạt điều giàu dinh dưỡng sánh mịn.",
  },
  {
    id: "prod-sua-2",
    name: "Sữa bò tươi - Bí đỏ Đậu phộng",
    categoryName: "Trạm Sữa",
    subCategory: "Sữa Hạt Tươi",
    image: "/images/products/suabido.png",
    price: 18000,
    isFeatured: false,
    isAvailable: true,
    unit: "Ly",
    description: "Ngọt sánh tự nhiên từ bí đỏ Đà Lạt và béo thơm từ đậu phộng rang thủ công.",
  },
  {
    id: "prod-sua-3",
    name: "Sữa bò tươi - Cốm rang",
    categoryName: "Trạm Sữa",
    subCategory: "Sữa Hạt Tươi",
    image: "/images/products/suacomrang.png",
    price: 25000,
    isFeatured: true,
    isAvailable: true,
    unit: "Ly",
    description: "Đặc sản sữa cốm rang thơm nồng nàn ấm áp giữa đêm Đà Lạt.",
  },
  {
    id: "prod-sua-4",
    name: "Trà sữa tươi - Olong matcha",
    categoryName: "Trạm Sữa",
    subCategory: "Trà Sữa Tươi",
    image: "/images/products/tsmatcha.png",
    price: 30000,
    isFeatured: true,
    isAvailable: true,
    unit: "Ly",
    description: "Matcha Nhật Bản cao cấp hòa quyện trà sữa tươi thanh ngọt, không hương liệu.",
  },
  {
    id: "prod-sua-5",
    name: "Trà sữa tươi - Olong gạo rang",
    categoryName: "Trạm Sữa",
    subCategory: "Trà Sữa Tươi",
    image: "/images/products/tsgaorang.png",
    price: 35000,
    isFeatured: true,
    isAvailable: true,
    unit: "Ly",
    description: "Vị trà gạo rang thơm lừng chuẩn vị trà sữa thủ công hiện đại.",
  },
  {
    id: "prod-sua-6",
    name: "Tam giác - nhân sữa",
    categoryName: "Trạm Sữa",
    subCategory: "Bánh Tam Giác Nướng",
    image: "/images/products/banhtamgiac.png",
    price: 20000,
    isFeatured: false,
    isAvailable: true,
    unit: "Cái",
    description: "Bánh nướng hình tam giác thơm lừng nhân sữa béo ngậy, ấm nóng.",
  },
  {
    id: "prod-sua-7",
    name: "Tam giác - nhân phô mai",
    categoryName: "Trạm Sữa",
    subCategory: "Bánh Tam Giác Nướng",
    image: "/images/products/banhtamgiac.png",
    price: 20000,
    isFeatured: false,
    isAvailable: true,
    unit: "Cái",
    description: "Nhân phô mai mặn ngọt béo thơm hấp dẫn kéo sợi hấp dẫn.",
  },
  {
    id: "prod-sua-8",
    name: "Tam giác - nhân trứng muối",
    categoryName: "Trạm Sữa",
    subCategory: "Bánh Tam Giác Nướng",
    image: "/images/products/banhtamgiac.png",
    price: 20000,
    isFeatured: true,
    isAvailable: true,
    unit: "Cái",
    description: "Trứng muối bùi béo kết hợp vỏ bánh giòn tan nóng hổi.",
  },

  // --- TRẠM BÁNH ---
  {
    id: "prod-banh-1",
    name: "Bánh tart trứng",
    categoryName: "Trạm Bánh",
    subCategory: "Bánh Tart",
    image: "/images/products/tarttrung.png",
    price: 18000,
    isFeatured: true,
    isAvailable: true,
    unit: "Cái",
    description: "Bánh tart ngàn lớp giòn rụm, nhân trứng nướng béo mịn tan trong miệng.",
  },
  {
    id: "prod-banh-2",
    name: "Bánh tart chuối choco",
    categoryName: "Trạm Bánh",
    subCategory: "Bánh Tart",
    image: "/images/products/tartchuoichoco.png",
    price: 20000,
    isFeatured: false,
    isAvailable: true,
    unit: "Cái",
    description: "Sự kết hợp hoàn hảo giữa chuối chín thơm lừng và sốt sô-cô-la ngọt ngào.",
  },
  {
    id: "prod-banh-3",
    name: "Cà phê đen",
    categoryName: "Trạm Bánh",
    subCategory: "Cafe Việt Nam",
    image: "/images/products/cfden.png",
    price: 18000,
    isFeatured: false,
    isAvailable: true,
    unit: "Ly",
    description: "Cà phê Robusta Đắk Lắk nguyên chất thơm đậm đà, vị đắng thanh quyến rũ.",
  },
  {
    id: "prod-banh-4",
    name: "Cà phê sữa",
    categoryName: "Trạm Bánh",
    subCategory: "Cafe Việt Nam",
    image: "/images/products/cfsua.png",
    price: 20000,
    isFeatured: true,
    isAvailable: true,
    unit: "Ly",
    description: "Cà phê sữa pha phin truyền thống thơm ngọt béo ngậy hài hòa.",
  },
  {
    id: "prod-banh-5",
    name: "Bạc xỉu",
    categoryName: "Trạm Bánh",
    subCategory: "Cafe Việt Nam",
    image: "/images/products/bacxiu.png",
    price: 25000,
    isFeatured: true,
    isAvailable: true,
    unit: "Ly",
    description: "Nhiều sữa ít cà phê, béo ngọt dịu nhẹ thích hợp nhâm nhi trò chuyện đêm.",
  },
  {
    id: "prod-banh-6",
    name: "Cà phê kem trứng",
    categoryName: "Trạm Bánh",
    subCategory: "Cafe Việt Nam",
    image: "/images/products/cfkemtrung.png",
    price: 30000,
    isFeatured: true,
    isAvailable: true,
    unit: "Ly",
    description: "Lớp kem trứng bông xốp đánh đặc quyện cùng cà phê nóng nồng nàn.",
  },
  {
    id: "prod-banh-7",
    name: "Bơ coco",
    categoryName: "Trạm Bánh",
    subCategory: "Đặc Biệt",
    image: "/images/products/bococo.png",
    price: 35000,
    isFeatured: true,
    isAvailable: true,
    unit: "Ly",
    description: "Bơ sáp Đà Lạt dầm nước cốt dừa béo thơm nức tiếng không thể bỏ lỡ.",
  },
  {
    id: "prod-banh-8",
    name: "Waffle bơ cay chà bông",
    categoryName: "Trạm Bánh",
    subCategory: "Bánh Waffle",
    image: "/images/products/banhwafflebocaychabong.png",
    price: 25000,
    isFeatured: false,
    isAvailable: true,
    unit: "Cái",
    description: "Waffle giòn rụm với bơ cay thơm cay kích thích và chà bông thơm lừng.",
  },
  {
    id: "prod-banh-9",
    name: "Waffle cốm dẻo",
    categoryName: "Trạm Bánh",
    subCategory: "Bánh Waffle",
    image: "/images/products/banhwafflecomdeo.png",
    price: 25000,
    isFeatured: false,
    isAvailable: true,
    unit: "Cái",
    description: "Waffle kết hợp hạt cốm non dẻo mềm thơm phức nướng giòn rụm viền ngoài.",
  },
  {
    id: "prod-banh-10",
    name: "Waffle kem choco",
    categoryName: "Trạm Bánh",
    subCategory: "Bánh Waffle",
    image: "/images/products/banhwafflekemchoco.png",
    price: 25000,
    isFeatured: true,
    isAvailable: true,
    unit: "Cái",
    description: "Waffle ấm nóng phủ kem socola béo ngậy ngọt ngào hấp dẫn.",
  },
];
